In [20]:
!git clone https://github.com/HeYantong/MSSP6070-Yantong.git

Cloning into 'MSSP6070-Yantong'...
remote: Enumerating objects: 88, done.
remote: Counting objects: 100% (88/88), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 88 (delta 36), reused 6 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (88/88), 3.64 MiB | 7.52 MiB/s, done.
Resolving deltas: 100% (36/36), done.

In [21]:
%cd /content/MSSP6070-Yantong

/content/MSSP6070-Yantong

In [22]:
!ls

Adding_File_Structure.py  data		    README.md
Assignments		  MSSP6070-Yantong  WeeklyModules

In [23]:
!ls data

 aapl.csv			  fb.csv    'Student Performance Data.csv'
 amzn.csv			  goog.csv
 data_academic_performance.xlsx   nflx.csv

In [24]:
import pandas as pd

df = pd.read_csv("data/Student Performance Data.csv")

df.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [25]:
filter_data = lambda x: x[x["admission prospect"] == "high"]

new_df = filter_data(df)

new_df

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
4,male,group C,some college,standard,76,78,75,229,none,high
5,female,group B,associate's degree,standard,71,83,78,232,none,high
6,female,group B,some college,standard,88,95,92,275,completed,high
...,...,...,...,...,...,...,...,...,...,...
990,male,group E,high school,free/reduced,86,81,75,242,completed,high
991,female,group B,some high school,standard,65,82,78,225,completed,high
995,female,group E,master's degree,standard,88,99,95,282,completed,high
998,female,group D,some college,standard,68,78,77,223,completed,high
999,female,group D,some college,free/reduced,77,86,86,249,none,high